install: true

jdk:
 - openjdk11


language: java

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

env:
  global:
    - MAVEN_OPTS="-Xmx3g"

cache:
    apt: true
    directories:
        - $HOME/.m2

services:
 - xvfb
    
script:
 - cd plugins/fr.lip6.puck.parent/  && mvn -e generate-sources install && cd -
 - mkdir website
 - cp -r plugins/fr.lip6.puck.parent/dsl/fr.lip6.puck.dsl.repository/target/repository website/updates  
 - cd plugins/fr.lip6.puck.parent/ && mvn -e generate-sources install site && mvn -e site:stage && cd -
 - cp -r plugins/fr.lip6.puck.parent/target/staging/apidocs website/
 - du -sh website/


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  on:
    branch: master


