/*
 * generated by Xtext 2.21.0
 */
package fr.lip6.puck.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PuckStandaloneSetup extends PuckStandaloneSetupGenerated {

	public static void doSetup() {
		new PuckStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
