/*
 * generated by Xtext 2.21.0
 */
package fr.lip6.puck.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.lip6.puck.dsl.PuckRuntimeModule;
import fr.lip6.puck.dsl.PuckStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PuckIdeSetup extends PuckStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PuckRuntimeModule(), new PuckIdeModule()));
	}
	
}
