/*
 * generated by Xtext 2.21.0
 */
package fr.lip6.puck.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PuckUiModule extends AbstractPuckUiModule {

	public PuckUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
