/*
 * generated by Xtext 2.21.0
 */
package fr.lip6.puck.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PuckRuntimeModule extends AbstractPuckRuntimeModule {
}
