name: Java CI with Maven

on: 
 push:
   branches: [ master ]

jobs:
  build:
    name: Maven
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.5
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Cache Maven packages
      uses: actions/cache@v2.1.5
      with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
    - name: destroy cache
      run: rm -rf ~/.m2
    - name: Build with Maven
      run: cd plugins/fr.lip6.puck.parent/ && mvn -T 4 -e generate-sources install && cd -
    - name: copy plugins 
      run: mkdir website ; cp -r plugins/fr.lip6.puck.parent/dsl/fr.lip6.puck.dsl.repository/target/repository website/updates ; cd plugins/fr.lip6.puck.parent/ && mvn -e generate-sources install site && mvn -e site:stage && cd - ; cp -r plugins/fr.lip6.puck.parent/target/staging/apidocs website/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true  